// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAYxsr_pOyIn7FilAjwLVLLXJVjGKhTqc',
    appId: '1:214467329976:web:d1b4921ee6c509ff8d994d',
    messagingSenderId: '214467329976',
    projectId: 'task-d628a',
    authDomain: 'task-d628a.firebaseapp.com',
    storageBucket: 'task-d628a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGHRq03R6rAzPgxMQcShnipMKOneGYjQ',
    appId: '1:214467329976:android:915f6e83a2381f778d994d',
    messagingSenderId: '214467329976',
    projectId: 'task-d628a',
    storageBucket: 'task-d628a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVLzd0EFgNn7lVbclVwjuf8vlHqmbcn2E',
    appId: '1:214467329976:ios:26567816847565b38d994d',
    messagingSenderId: '214467329976',
    projectId: 'task-d628a',
    storageBucket: 'task-d628a.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVLzd0EFgNn7lVbclVwjuf8vlHqmbcn2E',
    appId: '1:214467329976:ios:26567816847565b38d994d',
    messagingSenderId: '214467329976',
    projectId: 'task-d628a',
    storageBucket: 'task-d628a.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAYxsr_pOyIn7FilAjwLVLLXJVjGKhTqc',
    appId: '1:214467329976:web:987e46afc6465ed58d994d',
    messagingSenderId: '214467329976',
    projectId: 'task-d628a',
    authDomain: 'task-d628a.firebaseapp.com',
    storageBucket: 'task-d628a.firebasestorage.app',
  );
}
